# -*- coding: utf-8 -*-
"""Crawling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6fr7yXKc3nrct4kCcM6_sIizZ-8cIy6

<a href="https://www.youtube.com/channel/UC80kXszNqAdWGTHFBcOKVdg"><img src="https://lh3.googleusercontent.com/3BGYLiEKEvFZ0u6eLcDbKvad__jwIRs30D19_ttfwuMv2TrJ3qovD_Lb_HGF4QvSCeVYoE2Ay6Hkfx0wN0LFV1VvILg7XIdrqR7bE9EtnbF2SwYIueV1-B33aomEwjTmkAKDY4TYopVfaSbfsBWzwfOXpoKy_ASFSrjKt_2p_E35fyTkTbES2t9GUnZ25bMjAe_Y4xqfkw-8lRqK9zCYVwlcD_e2YXUlNXs8ubJCHwZp3MAdPL3kWzLMnuVAKsiORvjt_IgCVINNcDAqfak56arvmtg4MXpcbyKSeYK2A33p0jcFnOkgddq3KhABVNqb0PRM7inpysBXMJ7-u7Q__Y4LVGdFh_gTmuPcxHQZXqS10kU_K86bOQtgqY5m9DjJ5Ixd--sxiR4evRr4LnjDH-9L-6Rcu4EZI6LXMxlANCuFGuTLgIIqrq6qgIliinjuxyuwsX-cl-pE_Y3TBcZ5dum52_O8HtkuPo3NOQXD0Pg4ZfQV11CSkeD-82HaONupDREROrrgFOriOYljzSj4438GSaK4IUTfDjP1UFMKnA6QuZGhSA0noStBSeIwTitSUsHbspxGwYm05Of9UiP-vpvhB5zGDUWl2gLpPsXxz6SDNlDGsVFekX81jNOrFnDzj-Me98FgK4AAmW4Of6Z8LN1ZjBw1MdFwGabLN94tHUMg0sPf-UJFbw5XqN0spoltuB8YmAGSyIWLHoC4eVuARcEX=w1659-h300-no?authuser=0" align="center"></a>
# <center>Crawling Komentar Video Youtube</center>
<hr>

**Tujuan** dari program ini adalah melakukan crawling (pengambilan) data komentar pada sebuah video Youtube menggunakan **Youtube Data API v3**. Sebelum mencoba program ini, pastikan Anda sudah memiliki (mengaktifkan) layanan Youtube Data API dan telah membangkitkan **API Key**.

Jika belum memiliki **API KEY**, Anda dapat mengikuti petunjuk singkat sebagai berikut:
1. Login ke Google Developer Console (https://console.developers.google.com/)dengan akun Google Anda
2. Buat project baru dan lengkapi isian yang diminta.
3. Aktifkan Layanan API pada halaman project, dan cari **Youtube Data API v3**.
4. Dari halaman dashboard, buat kredential agar API tersebut dapat digunakan. Klik tombol **Buat Kredensial** (**Create Credential**). Lengkapi isian formnya.
5. Anda dapat mengakses / melihat API KEY pada tab **Credentials**.

## **Install Module**
"""

!pip install pandas
!pip install google-api-python-client

"""#1. Import Library"""

import pandas as pd
from googleapiclient.discovery import build

"""#2. Fungsi untuk crawling komentar"""

def video_comments(video_id):
	# empty list for storing reply
	replies = []

	# creating youtube resource object
	youtube = build('youtube', 'v3', developerKey=api_key)

	# retrieve youtube video results
	video_response = youtube.commentThreads().list(part='snippet,replies', videoId=video_id).execute()

	# iterate video response
	while video_response:

		# extracting required info
		# from each result object
		for item in video_response['items']:

			# Extracting comments ()
			published = item['snippet']['topLevelComment']['snippet']['publishedAt']
			user = item['snippet']['topLevelComment']['snippet']['authorDisplayName']

			# Extracting comments
			comment = item['snippet']['topLevelComment']['snippet']['textDisplay']
			likeCount = item['snippet']['topLevelComment']['snippet']['likeCount']

			replies.append([published, user, comment, likeCount])

			# counting number of reply of comment
			replycount = item['snippet']['totalReplyCount']

			# if reply is there
			# if replycount>0:
			# 	# iterate through all reply
			# 	for reply in item['replies']['comments']:

			# 		# Extract reply
			# 		published = reply['snippet']['publishedAt']
			# 		user = reply['snippet']['authorDisplayName']
			# 		repl = reply['snippet']['textDisplay']
			# 		likeCount = reply['snippet']['likeCount']

			# 		# Store reply is list
			# 		#replies.append(reply)
			# 		replies.append([published, user, repl, likeCount])

			# print comment with list of reply
			#print(comment, replies, end = '\n\n')

			# empty reply list
			#replies = []

		# Again repeat
		if 'nextPageToken' in video_response:
			video_response = youtube.commentThreads().list(
					part = 'snippet,replies',
					pageToken = video_response['nextPageToken'],
					videoId = video_id
				).execute()
		else:
			break
	#endwhile
	return replies

"""#3. Jalankan Proses Crawling"""

# isikan dengan api key Anda
api_key = 'AIzaSyCju_jmfd3gV4bNkJUopsME-rxqepFg9ZM'

# Enter video id
# contoh url video = https://www.youtube.com/watch?v=5tucmKjOGi8
video_id = "EdrnPfX4PKg" #isikan dengan kode / ID video

# Call function
comments = video_comments(video_id)

comments

"""#4. Ubah Hasil Crawling ke Dataframe"""

df = pd.DataFrame(comments, columns=['publishedAt', 'authorDisplayName', 'textDisplay', 'likeCount'])
df

"""#5. Simpan Hasil Crawling ke file CSV"""

df.to_csv('prabowo.csv', index=False)

"""# Ingin belajar lebih banyak lagi?

Banyak video pembelajaran terkait Machine Learning yang disajikan di channel Youtube http://youtube.com/c/AchmadSolichin. Silahkan berkunjung dan jangan lupa **SUBSCRIBE** untuk membantu pengembangan channel dengan video-video berkualitas lainnya.

## Terima kasih, selamat belajar!

Notebook ini dibuat oleh: <a href = "http://achmatim.net">Dr. Achmad Solichin</a> dengan acuan dari berbagai sumber:
1. https://www.geeksforgeeks.org/how-to-extract-youtube-comments-using-youtube-api-python/

<hr>
Copyright &copy; 2022 [Achmatim.Net](http://achmatim.net). This notebook and its source code are released under the terms of the CC License.​
"""